name: 🚀 SubLedger CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Run tests
        run: docker compose run --rm server npm test